- Cargo.lock
- Cargo.toml
- monocore/Cargo.toml
- monocore/README.md
- monocore/examples/orchestration_basic.rs
- monocore/examples/orchestration_load.rs
- monocore/lib/orchestration/orchestrator.rs
- monocore/lib/runtime/state.rs
- monocore/lib/runtime/supervisor.rs
This PR enhances the service status display in the orchestration examples by adding CPU and memory metrics monitoring, along with allocated resource information.
- Added real-time CPU usage monitoring using sysinfo
- Added memory usage monitoring in bytes
- Format CPU usage as percentage (e.g. "10%")
- Format memory usage in MiB (e.g. "168MiB")
- Added columns for allocated vCPUs and RAM
- Made MicroVmState thread-safe using Arc<Mutex>
- Added mutable getters for metrics updates
- Changed CPU usage type from f64 to f32 to match sysinfo
- Added documentation for metrics fields
- Added explicit RAM allocation in examples (200MB per service)
- Improved status display formatting and column alignment
- Added supervisor PID tracking and display
- Tested with both basic and load orchestration …
> feat: implement supervisor getting microvm cpu and mem usage and add to examples

- monocore/README.md
- monocore/examples/oci_pull.rs
- monocore/lib/oci/distribution/docker.rs
- monocore/lib/oci/distribution/traits.rs
- monocore/lib/utils/conversion.rs
- monocore/lib/utils/path.rs
This PR enhances OCI image handling and improves documentation across the monocore library.
- Add new `oci_pull.rs` example demonstrating OCI image pulling functionality
- Implement proper file structure for OCI artifacts with separate directories for repos and layers
- Add file path sanitization for repository names
- Improve error handling and validation in image pulling process
- Standardize directory naming conventions (e.g., `layer/` instead of `layers/`)
- Add constants for common filenames (`index.json`, `manifest.json`, `config.json`)
- Document complete directory structure in README with mermaid diagram
- Revamp monocore README with comprehensive feature overview
- Add detailed code examples for common use cases
- Include badges and warning about development status
- Improve API …
> feat: download image layers and artifacts in appropriate folders

- monocore/README.md
- monocore/bin/monocore.rs
- monocore/examples/microvm_curl.rs
- monocore/examples/microvm_nop.rs
- monocore/examples/microvm_shell.rs
- monocore/examples/microvm_tcp.rs
- monocore/examples/microvm_udp.rs
- monocore/examples/orchestration_basic.rs
- monocore/examples/orchestration_load.rs
- monocore/lib/cli/args.rs
- monocore/lib/error.rs
- monocore/lib/orchestration/down.rs
- monocore/lib/orchestration/log_policy.rs
- monocore/lib/orchestration/mod.rs
- monocore/lib/orchestration/orchestrator.rs
- monocore/lib/orchestration/remove.rs
- monocore/lib/orchestration/status.rs
- monocore/lib/orchestration/up.rs
- monocore/lib/utils/conversion.rs
- monocore/lib/utils/oci.rs
- monocore/lib/utils/path.rs
This PR refactors the orchestrator module to improve code organization and adds new service management features, including a CLI command for removing services. The changes make the codebase more maintainable and provide better tools for managing service lifecycles.
- Split `orchestrator.rs` into focused modules:
- `up.rs`: Service startup logic
- `down.rs`: Service shutdown handling
- `status.rs`: Status monitoring
- `remove.rs`: Service removal
- `log_policy.rs`: Log retention
- **Service Configuration Storage**
- Store service configs in `~/.monocore/service/[name]/`
- Persist service.json and group.json for each service
- Improve service state recovery
- **CLI Remove Command**
```bash
monocore remove service1 service2
monocore remove -g mygroup
```
- Validates services aren't running …
> refactor(orchestrator): reorganize code and improve service management

- monocore/README.md
- monocore/bin/monocore.rs
- monocore/lib/cli/args.rs
- monocore/lib/config/defaults.rs
- monocore/lib/lib.rs
- monocore/lib/server/handlers.rs
- monocore/lib/server/mod.rs
- monocore/lib/server/routes.rs
- monocore/lib/server/state.rs
- monocore/lib/server/types.rs
This PR adds a new server mode to monocore that exposes a REST API for managing services. The server provides endpoints for starting, stopping, checking status, and removing services.
- Added new `serve` subcommand to start monocore in server mode
- Implemented REST API endpoints:
- POST /up - Start services defined in config
- POST /down - Stop running services 
- GET /status - Get status of all services
- POST /remove - Remove service files
- Added server-related modules:
- handlers.rs - Request handlers for each endpoint
- routes.rs - API route definitions
- state.rs - Server state management
- types.rs - Request/response type definitions
- Updated README with API documentation and examples
- Added default server port (3000) configuration
The REST API allows monocore to be integrated …
> feat: Add REST API server mode

- Makefile
- README.md
- monocore/README.md
This PR revamps the project documentation to better communicate monocore's primary value proposition as a secure sandbox for AI code execution.
- **Clearer Value Proposition**: Refocused the README to emphasize monocore's role in secure AI code execution
- **Better Use Cases**: Added concrete examples of how AI agents can use monocore:
- Generating visualizations
- Running data analysis
- Testing generated code
- Executing system commands
- **Improved Getting Started**: New step-by-step guide with practical examples
- **Technical Accuracy**: Fixed path reference in orchestrator example code
- **Streamlined Structure**: Removed unused badges and simplified header section
```toml
[[service]]
name = "python-sandbox"
base = "python:3.11-slim"
ram = 512
cpus = 1
group = "sandboxes"
command = …
```
> chore: revamp README with focus on AI sandbox use case

- .gitignore
- Makefile
- build_libkrun.sh
- install_monocore.sh
- monocore/Makefile
- monocore/build.rs
- package_monocore.sh
- setup_env.sh
This PR significantly improves the installation experience by making it simpler and sudo-less by leveraging `~/.local` directories. The changes set up the project for a future `curl | sh` style installation while maintaining security and portability.
Key changes:
- Moves installation from system directories (`/usr/local`) to user's home (`~/.local`)
- Updates build system to use relative RPATHs for libraries
- Adds new installation and environment setup scripts
- Improves build process to package releases properly
- Updates gitignore and build configuration for better organization
- Part of larger effort to fix #51, #55, #56 and improve DX 
Tested the following installation flows:
1. Clean installation:
```
make build install
```
- Verified binaries installed to ~/.local/bin
- Verified …
> chore: simplify installation

- Cargo.toml
- release-please-config.json
Updates the `monoutils-store` dependency from v0.1.0 to v0.2.0 and modifies the release-please configuration to skip GitHub releases for `monofs` and `monoutils-store` packages.
N/A - Maintenance update
1. Run the full test suite to ensure the dependency update doesn't introduce any regressions
2. Verify that release-please still works correctly with the updated configuration
> chore(deps): update monoutils-store version and skip GitHub release

- monofs/examples/dir_ops.rs
- monofs/lib/filesystem/dir.rs
- monofs/lib/filesystem/dir/find.rs
- monofs/lib/filesystem/dir/ops.rs
- monofs/lib/filesystem/metadata.rs
The main changes include:
- Added deleted_at timestamp to track when entities are marked as deleted
- Modified find operations to skip deleted entities
- Changed remove behavior to soft delete by default
- Added remove_trace for complete removal
- Improved test coverage for deletion scenarios
- Updated documentation and examples
> feat(monofs): replace tombstone with deleted_at timestamp

- monofs/lib/filesystem/metadata.rs
Change the value type of extended attributes from String to Ipld to support storing more complex data types. This includes:
- Update BTreeMap value type from String to Ipld
- Modify get_attribute to return Option<&Ipld>
- Update set_attribute to accept any value that can convert to Ipld
- Adjust tests to handle Ipld::String values
- Remove Eq trait derivation since Ipld doesn't implement it
> feat(fs): support IPLD values in extended attributes

- monofs/README.md
- monofs/examples/dir_ops.rs
- monofs/lib/filesystem/cidlink.rs
- monofs/lib/filesystem/dir.rs
- monofs/lib/filesystem/dir/find.rs
- monofs/lib/filesystem/dir/ops.rs
- monofs/lib/filesystem/entity.rs
- monofs/lib/filesystem/error.rs
- monofs/lib/filesystem/file.rs
- monofs/lib/filesystem/metadata.rs
- monofs/lib/filesystem/symcidlink.rs
- monofs/lib/filesystem/sympathlink.rs
Changes:
- Changed Dir API to use async put_adapted_* methods instead of sync put_* methods
- Removed Dir.remove_trace() in favor of single Dir.remove() method
- Removed deleted_at from Metadata in favor of Entry.deleted flag
- Changed SyncType enum to include Default variant as default value
- Added Entry struct to track deletion status of directory entries
- Added versioning support to directory entries via put_adapted_* methods
- Simplified directory entry management with single remove() method
- Added convenience create_* methods for files, dirs and symlinks
- Updated examples and tests to use new async API
- Made debug implementations more detailed
- Added Default variant to SyncType enum
> refactor(monofs): improve directory entry versioning and deletion handling

- monofs/examples/dir_ops.rs
- monofs/lib/filesystem/dir.rs
- monofs/lib/filesystem/dir/ops.rs
- monofs/lib/filesystem/entity.rs
- monofs/lib/filesystem/file.rs
- monofs/lib/filesystem/file/io.rs
- monofs/lib/filesystem/symcidlink.rs
- monofs/lib/filesystem/sympathlink.rs
Add a new `checkpoint()` method to Dir, File, Entity, SymCidLink and SymPathLink that combines store() and load() operations into a single atomic operation. This simplifies the common pattern of storing and reloading entities to create new versions.
- Add checkpoint() method to all filesystem entities
- Update examples and tests to use checkpoint() instead of store()/load() pattern
- Fix move operation in Dir to avoid potential data loss during moves
- Update metadata modified timestamp when content changes
> feat(monofs): add checkpoint method to filesystem entities

- Cargo.lock
- monofs/examples/file_ops.rs
- monofs/lib/filesystem/dir/ops.rs
- monofs/lib/filesystem/entity.rs
- monofs/lib/filesystem/file.rs
- monofs/lib/filesystem/symcidlink.rs
- monofs/lib/store/flatfsstore.rs
- monofs/lib/store/membufferstore.rs
- monoutils-store/Cargo.toml
- monoutils-store/lib/error.rs
- monoutils-store/lib/implementations/chunkers/fastcdc.rs
- monoutils-store/lib/implementations/chunkers/gearcdc.rs
- monoutils-store/lib/implementations/layouts/balanced.rs
- monoutils-store/lib/implementations/layouts/flat.rs
- monoutils-store/lib/implementations/layouts/trickle.rs
- monoutils-store/lib/implementations/stores/dualstore.rs
- monoutils-store/lib/implementations/stores/memstore.rs
- monoutils-store/lib/layout.rs
- monoutils-store/lib/store.rs
- Split raw block operations into separate RawStore trait
- Change File::with_content to take AsyncRead instead of Into<Bytes>
- Make File::is_empty async and return FsResult
- Add get_bytes_size method to IpldStore trait
- Rename FastCDC to FastCDCChunker for clarity
- Rename GearCDC to GearCDCChunker for clarity
- Extracting raw block operations into a dedicated RawStore trait
- Making file operations more async-friendly and consistent
- Adding size tracking capabilities to store implementations
- Improving error handling and documentation
- Enhancing FastCDC chunker implementation with better docs and optimizations
> refactor(store): improve store interface and chunking implementation

- monofs/examples/file.rs
- monofs/examples/flatfs_monofs.rs
- monofs/lib/filesystem/dir/ops.rs
- monofs/lib/filesystem/file/io.rs
- monofs/lib/server/nfs.rs
- monoutils-store/lib/implementations/stores/memstore.rs
- Replace FileOutputStream shutdown() with flush() for better semantics
- Reorder flush and drop operations in file examples
- Change logging level from info to trace for file operations
- Remove unnecessary data clone in memstore tests
> refactor(monofs): replace shutdown with flush in file operations

- monofs/lib/config/default.rs
- monofs/lib/error.rs
- monofs/lib/management/init.rs
- monofs/lib/utils/env.rs
- monofs/lib/utils/path.rs
- Create symbolic link from mount directory to mfs_data_dir
- Add symlink creation during filesystem initialization
- Ensure direct access to data directory from mount point
- Add DEFAULT_MFSRUN_BIN_PATH constant for default binary location
- Add MFSRUN_BIN_PATH_ENV_VAR for configuring binary path via environment
- Implement resolve_mfsrun_bin_path() to locate binary
- Add MfsrunBinaryNotFound error for missing binary
> feat(monofs): create symbolic link to mfs_data_dir in mount directory and configurable mfsrun binary path

- monofs/examples/flatfs_store.rs
- monofs/lib/store/flatfsstore.rs
- monofs/lib/store/membufferstore.rs
- monoutils-store/lib/constants.rs
- monoutils-store/lib/implementations/chunkers/fastcdc.rs
- monoutils-store/lib/implementations/chunkers/fixed.rs
- monoutils-store/lib/implementations/chunkers/gearcdc.rs
- monoutils-store/lib/implementations/chunkers/mod.rs
- monoutils-store/lib/implementations/stores/dualstore.rs
- monoutils-store/lib/implementations/stores/memstore.rs
- monoutils-store/lib/lib.rs
- monoutils-store/lib/store.rs
- Increased default chunk sizes:
- Desired: 4KB -> 128KB
- Min: 2KB -> 32KB
- Max: 64KB -> 512KB
- Added DEFAULT_MAX_NODE_BLOCK_SIZE constant (1MB)
- Moved constants from chunkers to root level
- Updated stores to use new node block size limit
- Renamed methods for consistency:
- get_node_block_max_size() -> get_max_node_block_size()
- get_raw_block_max_size() -> get_max_raw_block_size()
> refactor(store): rename block size methods and adjust defaults

- .todo.md
- monoutils-store/lib/implementations/layouts/flat.rs
- monoutils-store/lib/implementations/stores/memstore.rs
- monoutils-store/lib/store.rs
- Add reference counting for stored blocks
- Implement garbage_collect method to remove unreferenced blocks
- Add recursive cleanup of dependencies when blocks are removed
- Add comprehensive tests for garbage collection scenarios
- Improve documentation of IpldStore trait methods
- Add Unknown variant to Codec enum
> feat(store): implement garbage collection for MemoryStore

- monofs/lib/store/flatfsstore.rs
- monofs/lib/store/layeredstore.rs
- monoutils-store/lib/implementations/stores/dualstore.rs
- monoutils-store/lib/implementations/stores/memstore.rs
- monoutils-store/lib/store.rs
- monoutils-store/lib/utils.rs
- Improved DualStore configuration with separate read_from and write_to options
- Added comprehensive documentation and examples for DualStore
- Added extensive test coverage for DualStore operations
- Renamed data parameter to node in IpldStore trait for consistency
- Added StoreConfig trait for configurable stores
- Updated Codec enum to handle unknown values
- Renamed make_cid to generate_cid for better semantic clarity
> refactor(store): improve DualStore configuration and documentation

- Cargo.lock
- monofs/Cargo.toml
- monofs/examples/flatfs_monofs.rs
- monofs/lib/filesystem/dir.rs
- monofs/lib/filesystem/dir/ops.rs
- monofs/lib/store/flatfsstore.rs
- monofs/lib/utils/dir.rs
- monofs/lib/utils/mod.rs
- monoutils-store/lib/implementations/chunkers/fastcdc.rs
- monoutils-store/lib/implementations/chunkers/gearcdc.rs
- monoutils-store/lib/implementations/stores/memstore.rs
Fix stack overflow in test_ops_rename by wrapping chunkers and layouts in Arc to avoid expensive cloning in MemoryStore and FlatFsStore. This significantly improves performance for deep recursive operations.
Key changes:
- Fix potential stack overflow in directory rename operations
- Wrap chunkers and layouts in Arc in MemoryStore and FlatFsStore
- Update FastCDC and GearCDC to use Arc for gear tables
- Add directory tree visualization utility as a bonus feature
The performance improvement is particularly noticeable in deep recursive operations like directory renames, where multiple store clones were previously occurring.
> perf(store): optimize chunker cloning in stores fixing stack overflow

- Cargo.lock
- monocore/lib/oci/implementations/docker.rs
- monofs/Cargo.toml
- monofs/examples/flatfs_monofs.rs
- monofs/examples/flatfs_store.rs
- monofs/lib/filesystem/dir.rs
- monofs/lib/filesystem/dir/ops.rs
- monofs/lib/server/server.rs
- monofs/lib/store/flatfsstore.rs
- monofs/lib/utils/dir.rs
- monofs/lib/utils/mod.rs
- monoutils-store/Cargo.toml
- monoutils-store/lib/implementations/chunkers/fastcdc.rs
- monoutils-store/lib/implementations/chunkers/gearcdc.rs
- monoutils-store/lib/implementations/stores/memstore.rs
- Make reference counting optional in FlatFsStore
- Add TypedBuilder for better store configuration
- Rename FlatFsStoreDefault to FlatFsStore
- Improve documentation for both stores
- Remove LRU dependency
- Simplify store constructors by using builder pattern
- Add tests for disabled reference counting
> refactor(store): make FlatFsStore refcounting optional and improve MemoryStore APIs

- Cargo.lock
- virtualfs/Cargo.toml
- virtualfs/lib/error.rs
- virtualfs/lib/filesystem.rs
- virtualfs/lib/implementations/memoryfs.rs
- virtualfs/lib/implementations/overlayfs.rs
- Add overlayfs implementation
- Modify VirtualFileSystem trait to use &Path instead of impl AsRef<Path>
- Add async-recursion dependency for recursive operations
- Add comprehensive test suite for OverlayFileSystem operations including:
- Copy-up behavior for writes and renames
- Whiteout file handling for removals
- Metadata preservation during operations
- Top layer modifications
- Add new error variant for overlay filesystem validation
- Remove redundant remove_directory method (consolidated into remove)
- Change write_file to take Pin<Box<dyn AsyncRead>> for better ergonomics
> refactor(virtualfs): implement overlayfs

- monocore/bin/monocore.rs
- monocore/lib/cli/args/monocore.rs
- monocore/lib/error.rs
- monocore/lib/management/db.rs
- monocore/lib/management/image.rs
- monocore/lib/management/mod.rs
- monocore/lib/management/models/mod.rs
- monocore/lib/management/models/sandbox.rs
- monocore/lib/management/orchestra.rs
- monocore/lib/management/rootfs.rs
- monocore/lib/management/sandbox.rs
- monocore/lib/oci/implementations/docker.rs
- monocore/lib/runtime/monitor.rs
Add ability to execute arbitrary commands in sandboxes instead of only running predefined scripts. This adds a new --exec/-e flag to both the 'run' and 'tmp' commands.
- Add exec option to sandbox and run-image CLI commands
- Make script parameter optional, defaulting to DEFAULT_SCRIPT
- Add validation to prevent using both script and exec together
- Update sandbox run functions to handle exec commands
- Fix rootfs script patching to properly handle script updates
- Refactor sandbox DB operations to use new Sandbox model
> feat(cli): add exec command to sandbox and run-image

- Cargo.lock
- monocore/Cargo.toml
- monocore/bin/monocore.rs
- monocore/lib/cli/args/monocore.rs
- monocore/lib/management/db.rs
- monocore/lib/management/mod.rs
- monocore/lib/runtime/monitor.rs
- Add new `log` subcommand to view sandbox logs
- Support following logs with `-f/--follow` flag using `tail -f`
- Support viewing last N lines with `-n/--tail` option
> feat(cli): add log subcommand for viewing sandbox logs

- .gitignore
- monocore/bin/mcrun.rs
- monocore/lib/cli/args/mcrun.rs
- monocore/lib/config/monocore/builder.rs
- monocore/lib/config/monocore/config.rs
- monocore/lib/error.rs
- monocore/lib/management/sandbox.rs
- monocore/lib/vm/builder.rs
- monocore/lib/vm/ffi.rs
- monocore/lib/vm/vm.rs
Add network scope configuration to control sandbox network isolation levels:
- Replace SandboxNetwork with simpler NetworkScope enum (none/group/public/any)
- Add --scope, --ip, and --subnet CLI flags to mcrun command
- Update MicroVm builder and config to support network scope settings
- Add FFI bindings for krun_set_tsi_scope to configure network backend
- Update tests and documentation for new network scope features
- Removes SandboxNetwork and SandboxNetworkReach in favor of NetworkScope enum. Existing configs using network.reach will need to be updated to use the new scope field.
The network scope controls sandbox network isolation:
- none: No network communication between sandboxes
- group: Communication only within subnet (default)
- public: Communication with non-private addresses …
> feat(network): add network scope configuration

- monocore/bin/mcrun.rs
- monocore/lib/management/rootfs.rs
- monocore/lib/management/sandbox.rs
- Make patch_with_virtiofs_mounts public and integrate into sandbox setup flow
- Add volume mount patching for both image and native rootfs types
- Update patching logic to handle both scripts and volume mounts
- Improve logging messages to reflect combined patching operations
> feat(rootfs): integrate virtiofs volume mounts into sandbox setup

- scripts/install_monocore.sh
- Rename monokrun binary to mcrun for consistency
- Add automatic self-codesigning of binaries on macOS systems
- Suppress codesign stderr output and continue on failure
> feat: add macOS codesigning and rename monokrun to mcrun

- microsandbox-core/bin/msb/handlers.rs
- microsandbox-core/bin/msb/main.rs
- microsandbox-core/lib/cli/args/msb.rs
- microsandbox-core/lib/config/microsandbox/builder.rs
- microsandbox-core/lib/config/microsandbox/config.rs
- microsandbox-core/lib/management/config.rs
- microsandbox-core/lib/management/mod.rs
- microsandbox-core/lib/management/sandbox.rs
- microsandbox-core/lib/management/toolchain.rs
- microsandbox-core/lib/utils/path.rs
- Add self subcommand for upgrade/uninstall functionality
- Replace verbose flag with granular log levels (error/warn/info/debug/trace)
- Add toolchain management module for handling installation/uninstallation
- Remove proxy configuration and env_file options
- Rename 'reach' parameter to 'scope' for network configuration
- Add scope option to temporary sandboxes
- Restructure install/uninstall commands
- Remove proxy configuration support
- Remove env_file option from sandbox config
- Rename network 'reach' to 'scope' in CLI and handlers
> feat: add self-management and improve logging

- microsandbox-core/bin/msb/handlers.rs
- microsandbox-core/bin/msb/main.rs
- microsandbox-core/lib/cli/args/msb.rs
- microsandbox-core/lib/management/image.rs
- microsandbox-core/lib/management/toolchain.rs
- Remove `start` subcommand in favor of using `run` with default script
- Reorder arguments in `run` and `script_run` handlers
- Update help text for CLI flags to be more consistent
- Change registry handling behavior for sandboxes.io
- Add aliases for common commands (r=run, t=tmp, i=install)
- Add SANDBOXES_REGISTRY constant and implement pull functionality
- Make shell argument required with default value
- Improve documentation for registry handling
- Standardize CLI flag descriptions
- Clean up imports and formatting
> refactor(cli): reorganize CLI arguments and improve registry handling

- Cargo.lock
- Makefile
- microsandbox-core/Cargo.toml
- microsandbox-core/lib/cli/args/msb.rs
- microsandbox-core/lib/management/image.rs
- microsandbox-core/lib/oci/implementations/docker.rs
- microsandbox-core/lib/utils/mod.rs
- microsandbox-core/lib/utils/viz.rs
- Add CLI visualization feature flag and dependencies (indicatif, once_cell, console)
- Implement progress bars and spinners for layer downloads and extraction
- Replace system tar with native implementation when cli-viz enabled
- Update package description to use "sandboxes" instead of "virtual machines"
- Make cli-viz a required feature for msb and msbrun binaries
The changes improve user experience by providing visual feedback during potentially long-running operations like image downloads and layer extraction.
> feat: add progress bars for image downloads and layer extraction

- microsandbox-core/lib/config/defaults.rs
- microsandbox-core/lib/config/microsandbox/builder.rs
- microsandbox-core/lib/config/microsandbox/config.rs
- microsandbox-core/lib/management/rootfs.rs
- microsandbox-core/lib/management/sandbox.rs
- microsandbox-core/lib/vm/builder.rs
- Move #[default] attribute from NetworkScope::Group to NetworkScope::Public
- Update SandboxBuilder and MicroVmConfigBuilder to use NetworkScope::default()
- Add DEFAULT_NETWORK_SCOPE constant
- Clean up imports in rootfs.rs
> refactor(scope): change default network scope to public

- microsandbox-core/lib/management/rootfs.rs
- microsandbox-core/lib/management/sandbox.rs
Add functionality to automatically configure DNS servers (1.1.1.1 and 8.8.8.8) in the sandbox's /etc/resolv.conf if no nameservers are defined. This ensures DNS resolution works by default in the sandbox environment.
- Add patch_with_default_dns_settings function to handle DNS configuration
- Add comprehensive test cases covering various scenarios
- Integrate DNS configuration into both image and native rootfs setup
> feat(rootfs): add default DNS server configuration

- microsandbox-core/lib/management/rootfs.rs
- microsandbox-core/lib/vm/vm.rs
- Use PathBuf import directly instead of fully qualified path
- Canonicalize host paths before adding them as virtiofs mounts to ensure absolute paths and resolve any symlinks
> fix: canonicalize host paths for virtiofs mounts

- microsandbox-cli/bin/msb/handlers.rs
- microsandbox-core/lib/runtime/monitor.rs
- Modify log path structure from `.menv/log/<config>-<sandbox>.log` to `.menv/log/<config>/<sandbox>.log`
- Add `generate_log_path` helper method in MicroVmMonitor
- Ensure parent directories are created before writing logs
- Update log_subcommand handler to use new path structure
This change improves log organization by namespacing logs under their respective config directories.
> refactor(logging): implement hierarchical log file organization

- microsandbox-cli/bin/msb/handlers.rs
- microsandbox-cli/bin/msb/main.rs
- microsandbox-cli/lib/args/msb.rs
- microsandbox-core/lib/management/db.rs
- microsandbox-core/lib/management/home.rs
- microsandbox-core/lib/management/image.rs
- microsandbox-core/lib/management/menv.rs
- microsandbox-core/lib/management/server.rs
- microsandbox-core/lib/oci/implementations/docker.rs
- microsandbox-core/lib/utils/viz.rs
- Add ability to clean specific sandboxes by name
- Add force flag to override config file checks
- Add config file parameter for targeted cleanup
- Update clean subcommand handler with new parameters
- Add database function to delete specific sandboxes
- Improve spinner visualization for cleanup operations
- Fix "for" to "to" in CLI argument help messages
- Remove redundant message strings from spinner finishes
> feat(clean): enhance sandbox cleanup functionality

- Cargo.lock
- Cargo.toml
- microsandbox-core/lib/management/menv.rs
- microsandbox-core/lib/management/rootfs.rs
- microsandbox-core/lib/management/sandbox.rs
Add xattr-based stat override functionality to ensure proper rootfs permissions inside containers. This sets user.containers.override_stat to "0:0:0555" on the rootfs directory.
Additional changes:
- Remove redundant gitignore update visualization
- Update version to 0.1.0-alpha
> feat(rootfs): add container stat override support

- Makefile
- microsandbox-cli/Cargo.toml
- microsandbox-cli/bin/msb/handlers.rs
- microsandbox-cli/bin/msb/main.rs
- microsandbox-cli/lib/args/msb.rs
- microsandbox-core/lib/management/toolchain.rs
- scripts/aliases/msi
- scripts/aliases/msr
- scripts/aliases/msx
- scripts/install_microsandbox.sh
- scripts/package_microsandbox.sh
- Add shell script aliases (msr, msx, msi) for common commands
- Rename 'tmp' subcommand to 'exe' for better clarity
- Update build system to handle new alias scripts
- Update installation/uninstallation to manage alias executables
- Update documentation and messages to use "executables" instead of "binaries"
> feat: add command aliases and rename tmp to exe

- Cargo.lock
- microsandbox-cli/bin/msb/handlers.rs
- microsandbox-cli/bin/msb/main.rs
- microsandbox-cli/lib/args/msb.rs
- microsandbox-core/Cargo.toml
- microsandbox-core/lib/error.rs
- microsandbox-core/lib/management/home.rs
- microsandbox-core/lib/management/menv.rs
- Move log viewing logic from handlers to menv module
- Add server log subcommand for viewing namespace logs
- Add command existence checks for tail utility
- Improve error messages for command not found cases
- Update CLI help text for clarity
> refactor(cli): implement server log subcommand

- microsandbox-cli/bin/msb/handlers.rs
- microsandbox-cli/bin/msb/main.rs
- microsandbox-cli/lib/args/msb.rs
- microsandbox-cli/lib/error.rs
- microsandbox-core/lib/management/menv.rs
- Add new `server list` subcommand to display sandboxes in a namespace
- Create reusable `show_list` function in menv module for consistent sandbox display
- Update existing list subcommand to use the new show_list function
- Add ConfigError variant to MicrosandboxCliError enum
> feat(cli): add server list command and unified sandbox listing

- Cargo.lock
- microsandbox-cli/bin/msb/handlers.rs
- microsandbox-cli/bin/msb/main.rs
- microsandbox-cli/lib/args/msb.rs
- microsandbox-core/Cargo.toml
- microsandbox-core/lib/management/orchestra.rs
- microsandbox-core/lib/management/sandbox.rs
Add new `status` (with aliases `ps` and `stat`) command to show resource usage statistics for running sandboxes. The command displays:
- Running status
- Supervisor and microVM PIDs
- CPU usage percentage
- Memory usage in MiB
- Disk usage of RW layers
- Live updating view in TTY environments
Also includes:
- Refactored exec path determination into separate function
- Added psutil and crossterm dependencies for monitoring
- Fixed server keygen arg name from all_namespaces to all
- Added rm alias for remove command
- Improved command descriptions
> feat(cli): add status command and resource monitoring

- scripts/install_microsandbox.sh
The installation script has been updated to use microsandbox version 0.1.0 instead of 0.2.1.
> fix(script): downgrade microsandbox version to 0.1.0 in script

- Cargo.lock
- Cargo.toml
- microsandbox-utils/lib/runtime/supervisor.rs
* Downgrade nix crate from 0.30 to 0.29 due to PTY functionality issues
* Remove unused AsFd import and update PTY code to use as_raw_fd()
* Clean up comment formatting in Cargo.toml
> fix: downgrade nix to 0.29 and fix PTY handling

- microsandbox-cli/bin/msb/handlers.rs
- microsandbox-cli/bin/msb/main.rs
- microsandbox-cli/lib/args/msb.rs
- microsandbox-cli/lib/args/msbrun.rs
- microsandbox-core/lib/config/path_pair.rs
- Removed separate -p/--path and -c/--config flags from all commands
- Added new -f/--file flag that handles both project and config paths
- Added parse_file_path helper to determine if input is directory or file
- Simplified init_subcommand to take single path parameter
- Added -x as short alias for --exec flag
- Changed -p to be short form of --port instead of --path
> refactor(cli): consolidate path and config flags into single --file flag

- CLOUD_HOSTING.md
- README.md
- SELF_HOSTING.md
- Extract cloud hosting section from SELF_HOSTING.md into new CLOUD_HOSTING.md
- Update self-hosting guide to reference the new cloud hosting guide
- Improve wording in README.md for getting started steps
> refactor: move cloud hosting guide to dedicated file

- Cargo.lock
- Cargo.toml
- README.md
- microsandbox-portal/examples/repl.rs
- microsandbox-portal/examples/repl_timer.rs
- microsandbox-portal/examples/rpc_command.rs
- microsandbox-portal/lib/handler.rs
- microsandbox-portal/lib/payload.rs
- microsandbox-server/lib/handler.rs
- microsandbox-server/lib/payload.rs
- scripts/install_microsandbox.sh
- sdk/python/microsandbox/command.py
- sdk/python/microsandbox/command_execution.py
- sdk/rust/src/command.rs
Rename RPC method from sandbox.command.execute to sandbox.command.run for better
consistency with other API methods. This includes:
- Updating method name in RPC handlers
- Renaming SandboxCommandExecuteParams to SandboxCommandRunParams
- Updating documentation and examples
- Updating Python and Rust SDK implementations
> refactor: rename sandbox.command.execute to sandbox.command.run

- README.md
- SELF_HOSTING.md
- Replace asciinema player with direct video element
- Streamline app hosting description
- Improve Projects section readability
- Streamline quick start section in README
- Add asciinema link for demo video
- Consolidate platform requirements into a single notice
- Simplify API key setup instructions
- Remove redundant server configuration details
> docs: update README with video demo and clearer copy 

- Cargo.lock
- Cargo.toml
- MCP.md
- README.md
- SELF_HOSTING.md
- docs/guides/mcp.md
- docs/index.md
- microsandbox-cli/lib/args/msb.rs
- microsandbox-core/Cargo.toml
- microsandbox-portal/Cargo.toml
- microsandbox-portal/examples/rpc_command.rs
- microsandbox-portal/examples/rpc_repl.rs
- microsandbox-portal/lib/portal/repl/nodejs.rs
- microsandbox-portal/lib/portal/repl/python.rs
- microsandbox-server/Cargo.toml
- microsandbox-server/lib/handler.rs
- microsandbox-server/lib/mcp.rs
- microsandbox-utils/Cargo.toml
- scripts/install_microsandbox.sh
- Downgrade to version 2024-11-05 because anything else won't work in Claude
- Bump version from 0.2.4 to 0.2.5 across all packages
- Add tar and flate2 dependencies to root Cargo.toml
- Clean up unused dependencies across multiple crates
- Fix JSON-RPC id field to use optional type
- Optimize imports with better organization
> fix: downgrade MCP protocol version an remove unused deps

- .github/vet/policy.yaml
- .github/workflows/vet-ci.yml
Ref: https://github.com/microsandbox/microsandbox/issues/260
As discussed in this issue, we are introducing [vet](https://github.com/safedep/vet) in CI for continuous scanning and vetting of OSS components used in this project , introduced via PR etc. for finding any vulnerability and malware. 
I have drawn inspiration from https://github.com/CircuitVerse/CircuitVerse ([PR #5114](https://github.com/CircuitVerse/CircuitVerse/pull/5114/)) project by having same minimal `Policy for vet` for starting. We can define policy of our own security requirements.
Currently our policy is configured to:
- Find any `High` and `Critical` Vulnurability
- Find any `malicious` packages
- Find any `un-maintained` packages. 
- Find any package with `low-popularity`
REF:
vet-action repo: …
> feat: add vet ci integration for OSS security auditing 

- Cargo.toml
Add LTO option in the root cargo.toml file for better smaller build sizes for release builds.
Previous: `msb` binary was about 15mb
After: `msb` binary was about 11mb.
addresses: #267 . pretty much a copy/paste and running. big thanks to the author
> feat: add lto for release builds
